default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("PGUSER", ENV["USER"]) %>
  password: <%= ENV.fetch("PGPASSWORD", "") %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>

development:
  <<: *default
  database: copro_health_map_development

test:
  <<: *default
  database: copro_health_map_test

production:
  primary:
    <<: *default
    database: copro_health_map_production
  cache:
    <<: *default
    database: copro_health_map_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: copro_health_map_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: copro_health_map_production_cable
    migrations_paths: db/cable_migrate
